# This is part of a GNU -*- Makefile -*-, to specify system-dependent 
# parts of the Makefile enviroment.
#
# This gets included as part of the GNU-Makefile used in each of 
# the subdirectories.
#
# Depending on your platform, you need to select the correct definition.
# Also, you need to edit the Makefile in the bin subdirectory.

LPR  = lpr
A2PS = a2ps -C --center-title='$$f' --footer="Nachos"
DOXYGEN = /soft/doxygen/bin/doxygen

################################################
# Note sur les options de compilation et d'assemblage
# -G0 sert à ne pas utiliser la section contenant les "petits" objets
#       (.sbss). L'éditeur de liens peut alors se trouver avec un trop
# 	grand nombre d'objets dans cette section, amenant au message
#	"relocation truncated to fit: R_MIPS_GPREL16"
#	(vient d'un bug du linker dans les binutils 2.11, devrait disparaitre
#	dans les version ultérieures ?)
################################################

#CFG = SPARC-irisa-locking
# CFG = SPARC-insa-etud
# CFG = SPARC-irisa
#CFG = i386-irisa
CFG = i386-mac

################################################
### SPARC-insa-etud Host
################################################
ifeq ($(strip $(CFG)),SPARC-insa-etud)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -DHOST_SPARC -DHOST_IS_BIG_ENDIAN -D_REENTRANT
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = -lsocket -lnsl

## MIPS target compilation toolchain
MIPS_PREFIX=/usr/local/gnu/stow/nachos-cc-3.3/bin/mipsel-nachos-elf-
MIPS_AS = $(MIPS_PREFIX)gcc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)gcc
MIPS_LD = $(MIPS_PREFIX)ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif # ifeq ($(CFG),SPARC-insa-etud)

################################################
### SPARC-irisa Host
################################################
ifeq ($(strip $(CFG)),SPARC-irisa)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -DHOST_SPARC -DHOST_IS_BIG_ENDIAN -D_REENTRANT
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = -lsocket -lnsl

## MIPS target compilation toolchain
MIPS_PREFIX=/udd/puaut/Heptane/share/heptane/tools/mips/
MIPS_AS = $(MIPS_PREFIX)cross-cc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)cross-cc
MIPS_LD = $(MIPS_PREFIX)cross-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif # ifeq ($(CFG),SPARC-irisa)


################################################
### SPARC-irisa-locking Host
################################################
ifeq ($(strip $(CFG)),SPARC-irisa-locking)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -DHOST_SPARC -DHOST_IS_BIG_ENDIAN -D_REENTRANT -DCACHELOCKING 
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = -lsocket -lnsl

## MIPS target compilation toolchain
MIPS_PREFIX=/udd/puaut/Heptane/share/heptane/tools/mips/
MIPS_AS = $(MIPS_PREFIX)cross-cc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)cross-cc
MIPS_LD = $(MIPS_PREFIX)cross-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = -DCACHELOCKING -DEXEC
MIPS_CFLAGS = -Wall -G0  -fpack-struct -fno-builtin -fomit-frame-pointer $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif # ifeq ($(CFG),SPARC-irisa-locking)


################################################
### i386-irisa Host
################################################
ifeq ($(CFG),i386-irisa)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -DHOST_i386 -DHOST_IS_LITTLE_ENDIAN -D_REENTRANT
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = # -lsocket -lnsl

## MIPS target compilation toolchain
MIPS_PREFIX=/udd/caps/crossMips/TOOLCHAIN/cross-tool/mips/
MIPS_AS = $(MIPS_PREFIX)cross-cc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)cross-cc
MIPS_LD = $(MIPS_PREFIX)cross-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif

################################################
### i386-mac Host
################################################
ifeq ($(CFG),i386-mac)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -DHOST_i386 -DHOST_IS_LITTLE_ENDIAN -D_REENTRANT
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = # -lsocket -lnsl

## MIPS target compilation toolchain
#MIPS_PREFIX=/Users/puaut/cross-cc-mips/mips/
MIPS_PREFIX=/udd/caps/crossMips/TOOLCHAIN/cross-tool/mips/
MIPS_AS = $(MIPS_PREFIX)cross-cc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)cross-cc
MIPS_LD = $(MIPS_PREFIX)cross-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif
